#!/bin/bash
#
# git-dude - Git commit notifier
# https://github.com/sickill/git-dude
#
# Copyright (C) 2011-2015 Marcin Kulik <http://ku1ik.com/>
#
# Distributed under the GNU General Public License, version 3.0.
# Indigo edit

set -e

interval=$(git config dude.interval || true)
interval=${interval:-60}
app_name=$(basename $0)

export LC_ALL=C # make sure git talks english

notify_cmd='notify-send -u critical "$TITLE" "$DESCRIPTION"'

function dudenotify() {
  local TITLE="$1"
  local DESCRIPTION="$2"

  if [ -n "$notify_cmd" ]; then
    eval $notify_cmd
  fi

  date "+%x %X"
  echo "$TITLE"
  if [ -n "$DESCRIPTION" ]; then
    echo "$DESCRIPTION"
  fi
  echo
}

[[ -d "$1" ]] && cd $1

while true; do
  for dir_name in *; do
    if [[ -d "$dir_name" && $(cd "$dir_name"; git rev-parse --git-dir 2>/dev/null) ]]; then

      if [[ $(cd "$dir_name"; git config dude.ignore) == true ]]; then
        continue
      fi
	  
      repo_name=$(basename "$dir_name" .git)
      notify-send "Checking dir:" "$dir_name"
      cd "$dir_name"

      changes=$(git fetch 2>&1 | grep -F -- '->' | sed 's/^ [+*=!-] //')

      while read -r line; do
        case $line in
          *..*)
            commit_range=$(echo "$line" | awk '{ print $1 }')
            branch_name=$(echo "$line" | awk '{ print $2 }')
            commit_messages=$(git log $commit_range --pretty=format:'%s (%an)')
            dudenotify "New commits in $repo_name/$branch_name" "$commit_messages"
            ;;
          *new\ branch*)
            branch_name=$(echo "$line" | awk '{ print $3 }')
            dudenotify "New branch $repo_name/$branch_name" ""
            ;;
          *new\ tag*)
            tag_name=$(echo "$line" | awk '{ print $3 }')
            dudenotify "New tag $repo_name/$tag_name" ""
            ;;
        esac
      done <<< "$changes"

      cd - &>/dev/null
    fi
  done
	notify-send "Done"
	exit 0
done
